language: java
jdk: oraclejdk11

script: mvn -e verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - ilg3109@gmail.com
    on_failure: always
    on_success: change
